[program:discord_rda]
directory=/opt/discord_rda
command=/usr/bin/env bundle exec ruby bot.rb
autostart=true
autorestart=true
startretries=3
stopsignal=TERM
stopwaitsecs=30
stdout_logfile=/var/log/discord_rda.stdout.log
stderr_logfile=/var/log/discord_rda.stderr.log
environment=RACK_ENV="production"
